### PR TITLE
Update 4-routing.md

### PR DESCRIPTION
**Pull request by ciceropablo**

### CODE REVIEW

**Comment by abagasra98** [comment]
@ciceropablo If I may ask, why did you add the statement to `import Redirect` in **App.js**. Since the `Redirect` module is never used in this file (at least not in Chapter 3), the project not only works fine without it, but it also removes the React compiler warning for `no-unused-var`.

**Comment by ciceropablo** [comment]
@abagasra98, exactly. It is only used in Chapter 9 (I think). Until then, the warning message appears.

**Comment by abagasra98** [comment]
@ciceropablo I'm still a bit confused. If it is not used until Chapter 9, why would we need to add the module here? From your commits, it seems that `Redirect` was not imported before, but you added it.

**Comment by ciceropablo** [comment]
@abagasra98, we had a bug before. Now we had a warning message. You can revert this and document better in Chapter 9. If you want.

**Pull request merged**
