### PR TITLE
Remove transparency to images in basic tutorial and add white background

### PR DESCRIPTION
**Pull request by davidatwhiletrue**
Images in the basic tutorial have been modified to add a white background. This way, content is visible when reading using -Reader mode- with a dark background.

PNG format is kept.

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
How can I test the `Reader Mode`?

**Comment by davidatwhiletrue** [comment]
In safari, click the reader button on the left of url bar. 




Enviado desde mi iPhone

**Comment by jonatasbaldin** [comment]
@nikolasburk can you take a look at this?

**Comment by swcarlosrj** [comment]
Thanks @davidatwhiletrue for opening this issue 😄. It was just fixed. Closing this!

**Pull request merged**
