### PR TITLE
Update routing (react-router-dom syntax)

### PR DESCRIPTION
**Pull request by giovannipds**
react-router-dom changed its syntax, this updates it

### CODE REVIEW

**Comment by giovannipds** [comment]
@TasinIshmam this one too, if you could, please help me to make this go forward. LMK if you have questions.

**Comment by giovannipds** [comment]
Additional info here: https://stackoverflow.com/a/69849271/842768

**Comment by TasinIshmam** [comment]
Thanks for bringing this up @giovannipds  :raised_hands: 

There seem to be other places where this needs to be changed as well: https://github.com/howtographql/howtographql/search?q=import+%7B+Route%2C+Routes+%7D+from+%27react-router-dom%27%3B 

Would you kindly consider adding those to this PR? (If you're not free to do this right now, that's okay too, let me know and I'll look into it later).

**Comment by giovannipds** [comment]
@TasinIshmam I'm following the tutorial, so I'll reach the pagination soon and open a PR for it.

**Comment by TasinIshmam** [comment]
> @TasinIshmam I'm following the tutorial, so I'll reach the pagination soon and open a PR for it.

Sounds good, I'll merge this then. Feel free to tag me in the new PR and I'll take a look.

**Comment by TasinIshmam** [comment]
@Pavanviky  could you kindly mention which error? 

The error related to this PR should have been fixed. I would suggest creating a new issue with details about the error you're getting and at what step of the tutorial it happens.

**Pull request merged**
