### PR TITLE
Updates ember-apollo tutorial

### PR DESCRIPTION
**Pull request by DevanB**
WIP 🎉

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
Hey @DevanB, do you need any help on this one?

Count on me!

**Comment by DevanB** [comment]
@jonatasbaldin I've got one and half more sections to complete updating. I have ran into a small issue in the authentication section due to the deprecation of route-actions, possibly.

Still trying to understand it all since I've not developed an Ember app in nearly a year.

**Comment by jonatasbaldin** [comment]
Cool @d4vidB! I'm not an Ember dev, so I can't help you on that :( but I can go through it to test the whole thing once u are done, just lmk :)

**Comment by ELepolt** [comment]
I know this was quite a bit ago, but any chance this can be updated and/or merged

**Pull request closed without merging**
