### PR TITLE
ruby formatting closes #891

### LINKED ISSUE #891: issues with ruby tutorial
re pr https://github.com/howtographql/howtographql/pull/890

I think I found a few more issues.

1. The `resolve` function in [3-mutations.md](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-ruby/3-mutations.md) throws and exception because it's missing an `end` keyword.

2. `rails generate graphql:install` seems to not create DateTimeType (used in [2-queries.md](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-ruby/2-queries.md)) or BaseMutations (used in [3-mutations.md](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-ruby/3-mutations.md)). Related issue https://github.com/howtographql/graphql-ruby/issues/20

I have the resolve error sorted already https://github.com/ConorSheehan1/howtographql/commit/8111e7ed098b4394b2a34d6a9a66b2d94f101ade, but I'm trying to figure out if the `DateTimeType` and `BaseMutations` issues could be down to gem versions or my environment.

Would you prefer if I wait and add all of those changes as one pr?
Or add them as separate prs?

### PR DESCRIPTION
**Pull request by ConorSheehan1**
fixes:
1. Missing `end` keyword in `resolve` function in [3-mutations.md](https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-ruby/3-mutations.md).  re https://github.com/howtographql/howtographql/issues/891
2.  `rails generate graphql:install` does not generate DateTimeType or BaseMutation. re https://github.com/howtographql/howtographql/issues/891
3. `ctx` is undefined, use context. re https://github.com/howtographql/howtographql/issues/104

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
Thanks for the PR @ConorSheehan1. I'm not a Ruby dev, so I'll wait for the @RStankov 	review (or for other ruby devs around to test it too)!

**Comment by RStankov** [comment]
@jonatasbaldin Looks good 🚀
@ConorSheehan1 thanks 🙌

**Comment by RStankov** [comment]
@jonatasbaldin Lets not merge this PR.

I opened a PR which fixes this issue 👉 https://github.com/howtographql/howtographql/pull/897

Covering scalar was not part of original tutorial. I have them in the Ruby, since there the code is more polished.

**Comment by jonatasbaldin** [comment]
Fixed at #897.

**Pull request closed without merging**
