### PR TITLE
Firefox bug: all endpoints point to introduction!

### PR DESCRIPTION
**Pull request by CodeAmend**
There is a Firefox error, at least, with the Grpahql-js tutorials. I tried end Chrome and it works. In Firefox, over and over again the bug continues.

I am not sure where to put this information. It would be nice if I knew how to find the code so I can edit it. This takes me a lot of time to write you guys, so please respond back with a proper way to let you know of these errors (so far found 2 and did 2 pull requests). 

Personally, I would rather find the code and do the editing myself so I can get some decent contributions. :)

### CODE REVIEW

**Comment by marktani** [comment]
Hey, I don't think we want to merge this PR, but maybe @timsuchanek can figure out the problem you encountered with Firefox. can you explain what you mean with endpoint?

**Comment by CodeAmend** [comment]
Basically all links would go to the [graphql-js page](https://www.howtographql.com/graphql-js/0-introduction/)

0-introduction <-- finished, clicked go to next section.
Url changed to `1-getting-started/` and it was the same page. I went ahead and did the quiz again, and clicked next section and ended up here `2-queries` but it was still the `0-introduction` content. Same for 
`3-mutations/`. 

Interesting enough, when I finished the same quiz it would mark the section as complete, so at one point I had all sections 0 -4 marked as complete but had only did the intro page. It was weird.

So I changed to Chrome. It worked and I continued the tutorial. I went back to Firefox and manually pasted in the links and it went to intro page each time. I just checked my github messages and tried Firefox again and now it is working. I am not sure how to reproduce it now.

**Comment by marktani** [comment]
I think this happens when a new version is deployed while you are on the website. this also happened to me on Chrome before

**Comment by marktani** [comment]
Anyway I am closing this PR. Please comment here or add a new issue if you have further questions :simple_smile:

**Pull request closed without merging**
