### PR TITLE
Fixes small typo in 2-queries.md

### PR DESCRIPTION
**Pull request by charmcitygavin**
The endpoint should be `/graphiql`, not `/graphql`.

### CODE REVIEW

**Comment by mairatma** [comment]
@charmcitygavin Thanks for helping out!

In this case, that's actually not true though. `endpointUrl` from `graphiqlExpress` should receive the url for the graphql endpoint, not for its own endpoint. Check out https://github.com/howtographql/graphql-js/blob/master/src/index.js#L41 for example, which is the main file for the repo containing the whole tutorial project. It's working as expected, with `/graphql`.

**Comment by marktani** [comment]
@mairatma does that mean all is fine already? 🙂

**Comment by mairatma** [comment]
Yes, the current code in the tutorial should be correct :)

**Comment by charmcitygavin** [comment]
Oh gosh, you're totally right! Thank you for explaining it to me. I'm really enjoying this tutorial! You did great work here. 😊

**Comment by mairatma** [comment]
I'm glad you're enjoying it! Feel free to continue coming with suggestions and fixes as you find any issues going through it 😄

**Comment by marktani** [comment]
Thanks, I'm closing this. Enjoy the tutorial, @charmcitygavin 🙌

**Pull request closed without merging**
