### PR TITLE
Update 1-getting-started.md

### PR DESCRIPTION
**Pull request by ciceropablo**

### CODE REVIEW

**Comment by marktani** [comment]
What's your reasoning behind proposing this change? Emojis are cool 🚀

**Comment by ciceropablo** [comment]
@marktani, sorry! I see that.

fireshot capture 2 - react relay - _ - https___www howtographql com_react-relay_1-getting-started_

**Comment by marktani** [comment]
It works for me:

image

Could you create [a new issue](https://github.com/howtographql/howtographql/issues/new) instead, that includes your browser/OS? 🙂

**Comment by ciceropablo** [comment]
@marktani, of course. Thank's!

**Pull request closed without merging**
