### PR TITLE
Update ruby tutorial

### PR DESCRIPTION
**Pull request by AlexVPopov**
This PR updates the Ruby tutorial for Rails 6 and does a couple of other small changes.

### CODE REVIEW

**Comment by AlexVPopov** [comment]
@RStankov I'll be updating the example app (https://github.com/howtographql/graphql-ruby) in the coming days to Rails 6 and Ruby 2.7.

**Comment by RStankov** [comment]
Thanks, looks good to me 🙌

**Comment by AlexVPopov** [comment]
Hey @Ex-Ark, thank you for spotting this. I've updated the PR.

**Comment by RStankov** [comment]
cc @nikolasburk Hey, can we merge this PR?

**Comment by nikolasburk** [comment]
Done, thanks a lot @AlexVPopov 🎉

**Pull request merged**
