### PR TITLE
fixes #301

### LINKED ISSUE #301: GraphQL-Python: mutate() got an unexpected keyword argument 'url'
I try follow https://www.howtographql.com/graphql-python/3-mutations/ but got error
"graphql.error.located_error.GraphQLLocatedError: mutate() got an unexpected keyword argument 'url' "

Code like:
# ...code
#1
class CreateLink(graphene.Mutation):
    id = graphene.Int()
    url = graphene.String()
    description = graphene.String()

    #2
    class Input:
        url = graphene.String()
        description = graphene.String()

    #3
    @staticmethod
    def mutate(root, input, context, info):
        link = Link(
            url=input.get('url'),
            description=input.get('description')
        )
        link.save()

        return CreateLink(
            id=link.id,
            url=link.url,
            description=link.description,
        )

#4
class Mutation(graphene.AbstractType):
    create_link = CreateLink.Field()

When try run:
mutation{
  createLink(
    url:"https://github.com/",
    description:"XXXXX"
  ){
    id
    url
    description
  }
}

Got error

### PR DESCRIPTION
**Pull request by SAThomsen**
Updated the code to the new mutation spec. Fixes #301

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
Hi, I've update the whole tutorial. This can actually be closed.

**Comment by jonatasbaldin** [comment]
Hey @SAThomsen or @nikolasburk, you may close this :)

**Comment by gc-codesnippets** [comment]
Awesome, thanks @SAThomsen and @jonatasbaldin 🙌

**Comment by nikolasburk** [comment]
Awesome, thanks a lot @SAThomsen and @jonatasbaldin 🙌

**Pull request closed without merging**
