### PR TITLE
[Chapter] Security

### PR DESCRIPTION
**Pull request by xuorig**

### CODE REVIEW

**Comment by xuorig** [comment]
@marktani or @nikolasburk I can't seem to have access to deploys, not sure why it's failing?

**Comment by marktani** [comment]
@nikolasburk do you have an idea?

**Comment by xuorig** [comment]
Alright! this should be good to go @nikolasburk & @marktani.

I added my bubble to the team in the same PR 👍

**Comment by nikolasburk** [comment]
Thanks a lot again Marc-Andre!! 🙏 And sorry for being unresponsive, I'm at a conference in London atm and don't check emails/GitHub often.

**Pull request merged**
