### PR TITLE
JSava riptconstant -> Javascript constant

### PR DESCRIPTION
**Pull request by misterbridge**
Fix typo

### CODE REVIEW

**Comment by misterbridge** [comment]
Ho boy ... :grin:

**Comment by misterbridge** [comment]
True ... true ...

**Comment by angly-cat** [comment]
And instead of making a lot of fixup commits, I'd suggest you squashing your commits first and then `git push -f` (or `--force`) to your branch.

**Comment by angly-cat** [comment]
It looks like this is your first PR, so I'll allow myself to give you some advice just in case you're not familiar with rebasing.

> squashing your commits

By that I meant running `git rebase -i head~3` (to interactively mess with order of last three commits) first and then changing the verb in the beginning of second commit from `pick` to `fixup` (or just `f`) and in the beginning of the third commit from `pick` to `squash` (or just `s`).

`fixup` commit will just amend into a previous, and `squash` is just like `fixup`, but let's you change a commit message afterwards.

And in case you're not familiar with VIM (the editor you likely gonna meet with while doing this), there're a lot of info about it on the Internet. But, basically, one needs to know that pressing `I` enters interactive (editing) mode, pressing `Esc` exits it, and presing `Shift+Z` twice saves a file.

**Comment by misterbridge** [comment]
I'm used to git commands that's just that I was doing those changes directly in github.com (which I'm not used to as a developer)
Yes that's my first PR ... **in github** :P
(I finally cloned it locally to make the changes, didn't find how to do this online)

**Comment by nikolasburk** [comment]
Hi @misterbridge! My sincere apologies for the delay in responding to your PR - unfortunately I wasn't able to put in much maintenance effort into How To GraphQL over the past months. However, I have just started a major cleanup and am taking a look at all issues & PRs.

As the `React & Apollo` tutorial recently saw a major update, this PR is now out-of-date. Still, thanks a lot for your contribution and please feel free to submit more PRs in the future! 🙏  🙂

**Pull request closed without merging**
