### PR TITLE
Fix for #993

### PR DESCRIPTION
**Pull request by tbrlpld**
As discussed in #993  , the `Input` class is not described in this chapter and the question/answer does not correspond with the code examples. The arguments for a mutation in this section are actually defined in the nested `Arguments` class. 
The proposed change reflects this. 

Also, the phrasing of the question was grammatically not ideal and was therefore changed too.

### CODE REVIEW

**Comment by tbrlpld** [comment]
@janpio Why was this closed? The issue still seems to be open.

**Comment by janpio** [comment]
Sorry, that was not intentional. We renamed the main branch from `master` to `main` and that unexpectedly closed this PR - sorry about that. Can you please open it again against `main`?

**Comment by tbrlpld** [comment]
No worries. Recreated in #1379

**Comment by janpio** [comment]
Thanks so much. Lucky GitHub keeps the diff around 😆 

(I closed around ~15 more PRs because of this... unexpected and unfortunate 😞 )

**Pull request closed without merging**
